version: "3.9"
services:
  api:
    build:
      context: .
      target: api
    environment:
      - TIDB_HOST=${TIDB_HOST}
      - TIDB_PORT=${TIDB_PORT}
      - TIDB_USER=${TIDB_USER}
      - TIDB_PASSWORD=${TIDB_PASSWORD}
      - TIDB_DATABASE=${TIDB_DATABASE}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "5173:80"
    depends_on:
      - api


